all: a.out
	./a.out
a.out:	$(SRC) 
	gcc -Iinc/ $(SRC)

SRC +=  main.c \
src/admin.c \
src/book_ticket.c \
src/cancel_ticket.c \
src/create_train.c \
src/load_traindata.c \
src/load_userdata.c \
src/print_ticket.c \
src/print_train.c \
src/Reload_traindata.c \
src/Reload_userdata.c \
src/user.c


	